server:
  port: 8811
spring:
  kafka:
    bootstrap-servers: localhost:29092
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/trophy-payment
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

